# Generated by Django 3.2.5 on 2021-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210721_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='mysite\x08log\\static\\img\x08g2.png', upload_to='images'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='myapp_image',
        ),
    ]
